sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

script:
  # Syntax check all php files and fail for any error text in STDERR
  - '! find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'
